// Generated by CoffeeScript 1.6.3
(function() {
  var _base, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.FE || (this.FE = {});

  (_base = this.FE).Views || (_base.Views = {});

  FE.Views.Day = (function(_super) {
    __extends(Day, _super);

    function Day() {
      _ref = Day.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Day.prototype.className = 'day';

    Day.prototype.appendHtml = function(collectionView, itemView, index) {
      var left, overlaps, width;
      overlaps = Math.max(1, collectionView.collection.groupFor(itemView.model).length - 1);
      width = 100 / overlaps;
      left = index % overlaps * width;
      itemView.$el.css({
        'top': "" + (itemView.model.get('start')) + "px",
        'left': "" + left + "%",
        'width': "" + width + "%",
        'height': "" + (itemView.model.length()) + "px"
      });
      return this.$el.append(itemView.el);
    };

    Day.prototype.itemView = FE.Views.Event;

    return Day;

  })(Marionette.CollectionView);

}).call(this);
