// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.FE || (this.FE = {});

  FE.Event = (function(_super) {
    __extends(Event, _super);

    function Event() {
      _ref = Event.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Event.prototype.overlapsWith = function(m) {
      return this.get('start') <= m.get('end') && this.get('end') >= m.get('start');
    };

    Event.prototype.length = function() {
      return this.get('end') - this.get('start');
    };

    Event.prototype.extendToInclude = function(m) {
      if (m.get('start') < this.get('start')) {
        this.set('start', m.get('start'));
      }
      if (m.get('end') > this.get('end')) {
        return this.set('end', m.get('end'));
      }
    };

    return Event;

  })(Backbone.Model);

}).call(this);
